### ISSUE TITLE
Candidate relocation filtering

### ISSUE THREAD

**Issue by noloman** [remotive-com/remote-jobs-api#6]
Hi folks!

If I make a request to the API and for example, I want to create a filter showing all the different options that the `candidate_required_location`, I get a huge list of different but yet kind of similar results, like:
- "USA Only"
- "North America Only"
- "Worldwide"
- "" (empty quotations that I assume means that there are no geographical restrictions?)
- "LATAM Only"
- "Latin America Only"
- "Americas Only"

Is there any chance you guys can apply some sort of filtering here in order to group those similar but yet different restrictions?

Thanks a lot!

**Comment by adriencombourieu** [comment]
When the location field is empty "" it means the location restriction is unknown to us. It should happen rarely.
